version: '3.8'
services:
  webapi:
    ports:
      - "5080:80"    # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    command: ["sh", "-c", "sleep 30 && dotnet WebApi.dll"]